Transform: AWS::Serverless-2016-10-31
Parameters:
  Net5LayerVersion:
    Type: String
    Description: Version number of the .NET 5 Lambda Layer to Use

Resources:
  LambdajectionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lambdajection
      Description: Lambda Layer for Lambajection
      CompatibleRuntimes:
        - provided.al2
      ContentUri: ../../bin/Layer/Debug/net5.0/layer

  CustomRuntime:
    Type: AWS::Serverless::Function
    Properties:
      Handler: CustomRuntime::Lambdajection.Examples.CustomRuntime.Handler::Run
      Runtime: provided.al2
      FunctionName: lambdajection-customruntime
      Timeout: 300
      CodeUri: ../../bin/Examples/CustomRuntime/Release/net5.0/linux-x64/publish/
      MemorySize: 512
      Layers:
        # https://github.com/cythral/dotnet-lambda-layer
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:net5:${Net5LayerVersion}
        - !Ref LambdajectionLayer
      Policies:
        - AWSLambdaExecute

Outputs:
  InputPayload:
    Value: "{}"

  ExpectedOutput:
    Value: '"Hello World!"'
