Transform: AWS::Serverless-2016-10-31
Resources:
  CustomRuntime:
    Type: AWS::Serverless::Function
    Properties:
      Handler: CustomRuntime::Lambdajection.Examples.CustomRuntime.Handler::Run
      Runtime: provided.al2
      FunctionName: lambdajection-customruntime
      Timeout: 300
      CodeUri: ../../bin/Examples/CustomRuntime/Release/net5.0/linux-x64/publish/
      MemorySize: 512
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:net5:3
      Policies:
        - AWSLambdaExecute

Outputs:
  InputPayload:
    Value: "{}"

  ExpectedOutput:
    Value: '"Hello World!"'
