Transform: AWS::Serverless-2016-10-31
Parameters:
  Net5LayerVersion:
    Type: String
    Description: Version number of the .NET 5 Lambda Layer to Use

  EncryptedValue:
    Type: String
    Description: A value for the encrypted options lambda to decrypt

Resources:
  EncryptedOptions:
    Type: AWS::Serverless::Function
    Properties:
      Handler: EncryptedOptions::Lambdajection.Examples.EncryptedOptions.Handler::Run
      Runtime: dotnetcore3.1
      FunctionName: lambdajection-encryptedoptions
      Timeout: 300
      CodeUri: ../../bin/Examples/EncryptedOptions/Release/netcoreapp3.1/publish/
      MemorySize: 512
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:net5:${Net5LayerVersion}
      Policies:
        - AWSLambdaBasicExecutionRole
        # Replace this with the ARN of a policy containing the kms:Decrypt permission
        - !ImportValue lambdajection-infrastructure:EncryptionKeyDecryptPolicyArn
      Environment:
        Variables:
          # Replace the value here with a KMS-encrypted string
          Lambda__EncryptedValue: !Ref EncryptedValue

Outputs:
  InputPayload:
    Value: "{}"

  ExpectedOutput:
    Value: '"Example Encrypted Value"'
