Transform: AWS::Serverless-2016-10-31
Resources:
  EncryptedOptions:
    Type: AWS::Serverless::Function
    Properties:
      Handler: EncryptedOptions::Lambdajection.Examples.EncryptedOptions.Handler::Run
      Runtime: dotnetcore3.1
      Timeout: 300
      CodeUri: ../bin/EncryptedOptions/Release/netcoreapp3.1/publish/
      MemorySize: 512
      Policies:
        - AWSLambdaExecute
        # Replace this with the ARN of a policy containing the kms:Decrypt permission
        - !ImportValue cfn-utilities:SecretsKeyDecryptPolicyArn
      Environment:
        Variables:
          # Replace the value here with a KMS-encrypted string
          Lambda__EncryptedValue: AQICAHh4uPV0nEVcHa3p2SypoTWL5pD0GFaoWYwOD6EQxbjUgAGMMsdjI4dFNfcZ0ise9vIAAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsM/ycznlHgrlC2bCAgEQgCRphMH2SwlU3BI+w0bXHPG8Y2ptoNQwiuNDLxlb2YZjxqhutVM=
